//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otoparkprojesi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteri
    {
        public int MusteriID { get; set; }
        public string MusteriTc { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public string MusteriTelefon { get; set; }
        public string AracPlaka { get; set; }
        public string AracMarka { get; set; }
        public string Konumu { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string AracUcret { get; set; }
        public Nullable<int> AracID { get; set; }
    
        public virtual AracTakip AracTakip { get; set; }
    }
}
