//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otoparkprojesi.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class otoparkEntities : DbContext
    {
        public otoparkEntities()
            : base("name=otoparkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AracTakip> AracTakip { get; set; }
        public virtual DbSet<musteri> musteri { get; set; }
        public virtual DbSet<yonetici> yonetici { get; set; }
    }
}
